name: untitledCinema
description: "Flutter application for 'UntitledCinema'."
publish_to: 'none'
version: 0.1.0


environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  # UI
  google_fonts: ^6.2.1
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.7
  cached_network_image: ^3.2.3

  # State Management
  provider: ^6.0.5

  # Network
  dio: ^5.3.2
  connectivity_plus: ^4.0.2
  http: ^1.1.0

  # Authentication
  google_sign_in: ^6.3.0

  # Local Storage
  shared_preferences: ^2.2.1

  # Utils
  equatable: ^2.0.7
  dartz: ^0.10.1
  get_it: ^7.6.0
  logger: ^2.0.1
  intl: ^0.18.1
  package_info_plus: ^4.1.0
  signalr_netcore: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/images/
    - assets/icons/

  uses-material-design: true
